
- name: create monitor directory
  file: 
    name: /opt/node
    state: directory

- name: Copy config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
     - { src: 'docker-compose.yml', dest: '/opt/node/docker-compose.yml'}

- name: Run containers
  shell:
    cmd: "docker compose up -d"
    chdir: /opt/node
    
