- name: Install
  apt: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ distrib1 }}"

- name: create keyrings directory
  file: 
    name: /etc/apt/keyrings
    state: directory

- name: add key and repo
  shell: "{{ item }}"
  with_items:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Install
  apt: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ distrib2 }}"