version: "3.4"
services:
  prometheus:
    image: quay.io/prometheus/prometheus
    container_name: prometheus
    volumes: 
       - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
       - "9090:9090"
    extra_hosts:
      - ${IP}

  grafana:
     image: grafana/grafana-oss
     container_name: grafana
     volumes: 
       - ./datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
     ports:
        - "3000:3000"
     depends_on:
       - prometheus
