global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
    - static_configs:
        - targets:
 #          - localhost:9093

#rule_files:
 # - "alerts.yml"
  
scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["node1:9100"]

  - job_name: "mysqld_exporter"
    static_configs:
      - targets: ["node1:9104"]

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ["node1:8080"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]